"use strict"

const ITCProtocol = {};
  ITCProtocol.PACKET_ENCAPSULATED = 0x01;
  ITCProtocol.PACKET_OPEN_SESSION = 0x02;
  ITCProtocol.PACKET_CLOSE_SESSION = 0x03;
  ITCProtocol.PACKET_INVALID_SESSION = 0x04;
  ITCProtocol.PACKET_SEND_QUEUE = 0x05;
  ITCProtocol.PACKET_ACK_NOTIFICATION = 0x07;
  ITCProtocol.PACKET_SET_OPTION = 0x07;
  ITCProtocol.PACKET_RAW = 0x08;
  ITCProtocol.PACKET_BLOCK_ADDRESS = 0x09;
  ITCProtocol.PACKET_UNBLOCK_ADDRESS = 0x10;
  ITCProtocol.PACKET_REPORT_PING = 0x11;
  ITCProtocol.PACKET_RAW_FILTER = 0x12;
  ITCProtocol.PACKET_SHUTDOWN = 0x7e;
  ITCProtocol.PACKET_EMERGENCY_SHUTDOWN = 0x7f; 

module.exports = ITCProtocol;